import Terminal from "#windows/Terminal";
import Safari from "./Safari";
import Resume from "./Resume";
import Finder from "./Finder";     
import Text from "./Text"; 
import Contacts from "./Contacts";  
import ImageViewer from "./ImageViewer";   
import Gallary from "./Gallary";     
import Vscode from "./Vscode";             
import AppleMusic from "./AppleMusic";       
import NotFound from "./NotFound";            
export { Terminal, Safari, Resume, Finder, Text, ImageViewer, Contacts, Gallary, Vscode, AppleMusic, NotFound};